### ISSUE TITLE
8 months since last release on crates.io. When can I expect 0.6?

### ISSUE THREAD

**Issue by lokegustafsson** [paperclip-rs/paperclip#329]
As the title says, it has been quite a while since last release. In particular, it would be really nice if #289 was available from crates.io. When can I expect it to be? Is there anything I can do to speed that up other than asking nicely?

**Comment by lokegustafsson** [comment]
Given the amount of wrapping going on in the actix-web plugin, maybe the long term aim should be to get the plugin part of paperclip upstreamed?

**Comment by ja573** [comment]
Probably more than you'd want, given #308

**Comment by lokegustafsson** [comment]
Yes, there will be less work on this than there used to be. But is it not preferable to deal with that by having smaller releases rather than similar releases less often?

**Comment by tiagolobocastro** [comment]
Hey, I've been trying to get things rolling and merging some of the existing PR's. Once #334 and #331 go in I can try to release 0.6. I'm not sure how that bit will work exactly as the crate might still be tied to @wafflespeanut and we might need to move it to paperclip-rs if possible.

**Comment by tiagolobocastro** [comment]
```
error: failed to publish to registry at https://crates.io

Caused by:
  the remote server responded with an error: A verified email address is required to publish crates to crates.io. Visit https://crates.io/me to set and verify your email address.
```

@wafflespeanut could you please add me? thanks
