### ISSUE TITLE
[Actix] If both a GET and POST is defined on the same path,  only one gets included

### ISSUE THREAD

**Issue by TobiasDeBruijn** [paperclip-rs/paperclip#380]
Noticed this issue today while checking the spec manually. I've got the following routes:
```rs
.route("[..]/wifi", web::get().to(endpoints::v1::[..]::get))
.route("[..]/wifi", web::post().to(endpoints::v1::[..]::set))
```
Where `[..]` indicates a path that has been left out. Only the `POST` endpoint is in the spec, the `GET` is not.

## Versions
- Actix: `3.3.3`
- Paperclip: Local fork (see #373), essentially v0.6.1
- Rust: `1.58`

**Comment by tiagolobocastro** [comment]
Oh interesting, I'll take a look at this.

**Comment by tiagolobocastro** [comment]
Hmm works for me... We also have a test that ends up doing this, though through the use of the proc-macros: `test_method_macro`

**Comment by TobiasDeBruijn** [comment]
Thats definitely odd. I've looked through it again and the spec for the `GET` request is not generated for me. To maybe paint a fuller picture as to what could cause this:
- [Full spec](https://paste.md-5.net/xutajihata.json)
- [Actix route declarations](https://paste.md-5.net/unibuzehok.php)
I unfortunately cannot share the full code base, as it is not opensource unfortunately.

However hopefully this could give some clues as to what might cause this, be it user error or paperclip.

Thanks :D

**Comment by tiagolobocastro** [comment]
Yes I can only see the post... does it work from the actix server standpoint, are both get and post working?

**Comment by TobiasDeBruijn** [comment]
Yep, both POST and GET work (and do the correct thing)

**Comment by tiagolobocastro** [comment]
Different might be that you're using `scope` and the tests don't do that?

**Comment by fritterhoff** [comment]
Any update on this issue? I also stumbled over that problem ;)

**Comment by fritterhoff** [comment]
I may be wrong but from my point of view the error gets caused here:
https://github.com/paperclip-rs/paperclip/blob/ef6eb8d57b44161c5a063840d874837507a06e43/plugins/actix-web/src/web.rs#L460

In case of multiple services located at the same path `insert` simply overwrites the existing definition.

**Comment by TobiasDeBruijn** [comment]
Could we maybe fix this by prefixing `p` with the method type? e.g. `/foo` becomes `get_/foo`? I haven't dug into the inner workings of this bit of Paperclip yet, so I'm unsure what it could break.

**Comment by fritterhoff** [comment]
From my point of view, I think this will break the definition since this is the path of the endpoint. So the swagger/openapi defintion will be `get_/foo` afterwards 😉

**Comment by fritterhoff** [comment]
Sadly I don't understand how the spec is build in case of the version without `scope`. I think it would make sense to stick to that solution - if possible - and reuse it 😁

**Comment by tiagolobocastro** [comment]
I think the issue here is that we're inserting a new item, rather than updating what's already there. If one of you wants to try that fix please go ahead, otherwise I'll try to get a fix till the weekend as time permits.

**Comment by fritterhoff** [comment]
I think I've found a solution, but I think it's a bit hacky.
