### ISSUE TITLE
Add support for `IpAddr`

### ISSUE THREAD

**Issue by RemiKalbe** [paperclip-rs/paperclip#381]
Getting the following error if I want to use `IpAddr` with `Apiv2Schema`
```rust
the variant or associated item `raw_schema` exists for enum `std::net::IpAddr`, but its trait bounds were not satisfied

variant or associated item cannot be called on `std::net::IpAddr` due to unsatisfied trait bounds

note: the following trait bounds were not satisfied:
      `std::net::IpAddr: paperclip::v2::schema::TypedData`
      which is required by `std::net::IpAddr: paperclip::v2::schema::Apiv2Schema`
      `&std::net::IpAddr: paperclip::v2::schema::TypedData`
      which is required by `&std::net::IpAddr: paperclip::v2::schema::Apiv2Schema`
      `&mut std::net::IpAddr: paperclip::v2::schema::TypedData`
      which is required by `&mut std::net::IpAddr: paperclip::v2::schema::Apiv2Schema`
```
```rust
#[derive(Debug, Serialize, Apiv2Schema)]
pub struct SmartReserveWorkerResponse {
    ...
    pub server_external_ip: IpAddr,
    ...
}

```

**Comment by tiagolobocastro** [comment]
Hey @RemiKalbe,

Sorry about that, looks like we're not handling `IpAddr`. Have a looksie at what we do for other types around [here](https://github.com/paperclip-rs/paperclip/blob/3acc864ab0ddf27b3a1234b49b1f43cdcefa490a/core/src/v2/schema.rs#L224).
If you're feeling like having a go at it and raising a PR for it please go ahead, otherwise I'll have a look later or over the weekend.

**Comment by tiagolobocastro** [comment]
@RemiKalbe, so we can add `IpAddrV4` and `IpAddrV6` as type `string` and format `ipv4` and `ipv6`. 
IpAddr is different, it's a `oneOf` basically, AFAIK is not present on openapi version 2.0 ?

**Comment by RemiKalbe** [comment]
Hey @tiagolobocastro sorry for the late reply! I was gonna suggest that `IpAddr` be treated as just 'an ip' rather than one Of `ipv4` or `ipv6`, but you already did it.

Thank you very much :)

**Comment by tiagolobocastro** [comment]
Yeah I was making it to be more complicated than it ought to :)
I'll attempt to publish a new version soon so you can pull it from crates.io.
