### ISSUE TITLE
Update licenses

### ISSUE THREAD

**Issue by Siphalor** [paperclip-rs/paperclip#390]
The [current MIT license](https://github.com/paperclip-rs/paperclip/blob/master/LICENSE-MIT) only covers the former maintainer and only gives 2019 as copyright year.

The [current Apache license](https://github.com/paperclip-rs/paperclip/blob/master/LICENSE-APACHE) uses `Copyright 2018 Yoshua Wuyts`.

**Comment by wafflespeanut** [comment]
That's a copy-pasta. And yes please. Let's change both to "Paperclip Contributors". Can't believe I had his name for so long.

**Comment by shymega** [comment]
This is fixed by #470, so it can be closed 💯
