### ISSUE TITLE
Options for manually extending

### ISSUE THREAD

**Issue by fritterhoff** [paperclip-rs/paperclip#399]
I'm evaluating paperclip in combination with actix-web. My project applies several middlewares that may cause different errors.

Is there an option to manually apply some changes on the spec (e.g. adding the error codes for a complete scope)?

**Comment by tiagolobocastro** [comment]
Yes, for example, you can provide an initial spec with `wrap_api_with_spec`, see an example [here](https://github.com/paperclip-rs/paperclip/blob/9bdd28343c6895a6e4ecbf1323bac38d0f052aeb/tests/test_app.rs#L1604). You may also modify on your handler it before presenting it, by using `with_raw_json_spec`.

What is your use case for error codes? For example, you can configure your error with `api_v2_errors`, see example [here](https://github.com/paperclip-rs/paperclip/blob/9bdd28343c6895a6e4ecbf1323bac38d0f052aeb/tests/test_app.rs#L2514).

**Comment by fritterhoff** [comment]
> Yes, for example, you can provide an initial spec with wrap_api_with_spec, see an example [here](https://github.com/paperclip-rs/paperclip/blob/9bdd28343c6895a6e4ecbf1323bac38d0f052aeb/tests/test_app.rs#L1604). You may also modify on your handler it before presenting it, by using with_raw_json_spec.

I'll check that the next days. Maybe I can figure out a way that can help me.

 > What is your use case for error codes? For example, you can configure your error with api_v2_errors, see example [here](https://github.com/paperclip-rs/paperclip/blob/9bdd28343c6895a6e4ecbf1323bac38d0f052aeb/tests/test_app.rs#L2514).

Well yeah that works fine as long as you define the errorcodes on the handler it self. But my middleware or extractors terminate with some errors (e.g. an status 500 or 403). Sure I could create some more or less empty structs and change the return type of all handlers, but I hoped there is an easier way to manage this.

**Comment by fritterhoff** [comment]
Found a feasible solution.
