### ISSUE TITLE
Dependency version conflict when trying to use actix4

### ISSUE THREAD

**Issue by Jawbone999** [paperclip-rs/paperclip#405]
I'm trying to migrate to `actix4` with `paperclip` but running into an issue with versioning `pin-project-lite`.

Adding the dependency like this...
`paperclip = { git = "https://github.com/paperclip-rs/paperclip", rev = "a0e9d32", features = ["actix4"], optional = true }`

...fails with this message:
```
error: failed to select a version for `pin-project-lite`.
    ... required by package `actix-web v4.0.0`
    ... which satisfies dependency `actix-web4 = "^4"` of package `paperclip-actix v0.4.2 (https://github.com/paperclip-rs/paperclip?rev=a0e9d32#a0e9d329)`
    ... which satisfies git dependency `paperclip-actix` of package `paperclip v0.6.1 (https://github.com/paperclip-rs/paperclip?rev=a0e9d32#a0e9d329)`
    ... which satisfies git dependency `paperclip` of package `MY_PACKAGE`
versions that meet the requirements `^0.2.7` are: 0.2.8, 0.2.7

all possible versions conflict with previously selected packages.

  previously selected package `pin-project-lite v0.2.6`
    ... which satisfies dependency `pin-project-lite = "^0.2.4"` (locked to 0.2.6) of package `futures-util v0.3.13`
    ... which satisfies dependency `futures-util = "^0.3.1"` (locked to 0.3.13) of package `actix-service v1.0.6`
    ... which satisfies dependency `actix-service1 = "^1"` (locked to 1.0.6) of package `paperclip-actix v0.4.2 (https://github.com/paperclip-rs/paperclip?rev=a0e9d32#a0e9d329)`
    ... which satisfies git dependency `paperclip-actix` of package `paperclip v0.6.1 (https://github.com/paperclip-rs/paperclip?rev=a0e9d32#a0e9d329)`
    ... which satisfies git dependency `paperclip` of package `MY_PACKAGE`

failed to select a version for `pin-project-lite` which could resolve this conflict
```

It looks to me like it has something to do with using both actix-service1 and actix-service2 in `paperclip-actix`, but my few attempts at fixing it myself still failed.

Any support here would be appreciated. Also updates crates.io pls thx

**Comment by tiagolobocastro** [comment]
If that is the case, would you mind point to https://github.com/paperclip-rs/paperclip/tree/service_opt to see if it fixes it? Thanks

**Comment by Jawbone999** [comment]
Thanks for the quick response. It looked to me like your fix didn't work, but then I tried rebuilding my project from scratch (`cargo clean` and without a `Cargo.lock` file) and it looks like the lock file was the culprit. It is now compiling on both your `service_opt` branch and the `main` branch.

Sorry for making an issue when it was ultimately something on my end! Though I do think your change to stop pulling in both version of `actix-service` is a good addition regardless.
