### ISSUE TITLE
how to known paperclip support features detail ? 

### ISSUE THREAD

**Issue by baoyachi** [paperclip-rs/paperclip#409]
* What does `paperclip` roadmap？
* how to known `paperclip` support features？

**Comment by tiagolobocastro** [comment]
> * What does `paperclip` roadmap？
No roadmap currently. Sadly we don't have enough active maintainers to work on such things.
 
>     * how to known `paperclip` support features？
The best is probably to search the test code. Our docs are a bit lacking, to say the least :upside_down_face:

**Comment by baoyachi** [comment]
😭
