### ISSUE TITLE
ability to set example for string responses

### ISSUE THREAD

**Issue by Tricked-dev** [paperclip-rs/paperclip#417]
There's no way to change the example from a string i suggest that there should be a way to do this

```rs
#[derive(Apiv2Schema, Serialize, Deserialize, Clone)]
pub struct Example {
  /// Foo
  /// * bar
  pub foo: String,
  // or
  /// Foo
  #[openapi(example = "bar"]
  pub foo: String
}
```

The same would apply to to bool/int keys. Ints currently default to 0 and booleans to true.

**Comment by rlebran** [comment]
Hey! I was looking at it few days ago but didn't commit anything yet. Might have something pretty soon thought

**Comment by dunnock** [comment]
This issue seems complete?

**Comment by rlebran** [comment]
Yes, this issue should be fixed
