### ISSUE TITLE
macros only work with HttpResponseWrapper return type?

### ISSUE THREAD

**Issue by snaggen** [paperclip-rs/paperclip#425]
I have a simple function with the following 
```rust
#[delete("/{url:.*}")]
pub async fn delete(
    path: web::Path<Url>,
    session: web::Data<Session>,
    apikey: ApiKey,
) -> Result<NoContent, ApiError> {
NoContent
}
```

This gives me the following error:
```
error[E0271]: type mismatch resolving `<impl futures::Future<Output = Result<NoContent, ApiError>> as futures::Future>::Output == HttpResponseWrapper`
   --> fileop-api-rs/src/api/v1.rs:169:1
    |
169 | #[delete("/{url:.*}")]
    | ^^^^^^^^^^^^^^^^^^^^^^ expected struct `HttpResponseWrapper`, found enum `Result`
    |
    = note: expected struct `HttpResponseWrapper`
                 found enum `Result<NoContent, ApiError>`
    = note: required because of the requirements on the impl of `Apiv2Operation` for `impl futures::Future<Output = Result<NoContent, ApiError>>`
```
Using ```#[api_v2_operation]``` and  ```.service(web::resource("/{url:.*}").route(web::delete().to(delete)))``` works as expected. However, I really prefer the to use ```#[delete("/{url:.*}")]``` and ```.service(delete)``` to keep the information with the function. 

Note, using git snapshot from May 12. Revision 4c1230ce9f790e4b4f3cdb261f53d69f4fde546d

**Comment by rlebran** [comment]
Hi, even when using the `#[delete("whatever")]` macro you need to use the `#[api_v2_operation]` for paperclip to work.

You can find an example [here](https://github.com/paperclip-rs/paperclip/blob/4c1230ce9f790e4b4f3cdb261f53d69f4fde546d/tests/test_app.rs#L3939)

**Comment by snaggen** [comment]
Ahh... Thanks for the info, will try that.

**Comment by snaggen** [comment]
Yes, that worked. Sorry for the noise.
