### ISSUE TITLE
Consider using `std::sync` instead of parking_lot

### ISSUE THREAD

**Issue by matklad** [paperclip-rs/paperclip#438]
paperclip today uses parking_lot. parking_lot provides faster, smaller mutexes, at the cost of adding a somewhat churn-prone dependency. It's not uncommon for downstream projects to end up with a couple of different versions of parking_lot in the Cargo.lock.

Naively, I would assume that mutext perfomance should not matter for the thing that paperclip is doing, and that sticking with std mutexes would make more sense, especially in the light of https://github.com/rust-lang/rust/pull/95035.

**Comment by tiagolobocastro** [comment]
I believe you are right, mutex performance should not be critical here.
One snag might be the usage of parking_lot mutex on the autogenerated client code via [CLI](https://paperclip-rs.github.io/paperclip/cli.html), as that is a public api.

As an aside, it's interesting how it's being used there. At a first glance, not sure why we need the response wrapped in a mutex.
```rust
    pub enum ApiError<R: Debug + Send + 'static> {
        #[error("API request failed for path: {} (code: {})", _0, _1)]
        Failure(String, http::status::StatusCode, Mutex<R>),
        #[error("Unsupported media type in response: {}", _0)]
        UnsupportedMediaType(String, Mutex<R>),
        #[error("An error has occurred while performing the API request: {}", _0)]
        Reqwest(reqwest::Error),.......
    }
```
