### ISSUE TITLE
The published version is not the latest.

### ISSUE THREAD

**Issue by kenkoooo** [paperclip-rs/paperclip#449]
Since we haven't published it to [crates.io](https://crates.io/) for a long time, there are many undelivered updates. Do we want to publish the latest one?

**Comment by tiagolobocastro** [comment]
Hi @kenkoooo, apologies I've been a bit busy with PL, but I'll try to look at this during the week. Please ping me on discord if I forget.

**Comment by kenkoooo** [comment]
@tiagolobocastro Cool! Thank you so much! I'm looking forward to getting the latest one :+1:

**Comment by tiagolobocastro** [comment]
I've published [v0.7.1](https://github.com/paperclip-rs/paperclip/releases/tag/v0.7.1) :tada:
