### ISSUE TITLE
Enable Hacktoberfest participation

### ISSUE THREAD

**Issue by dunnock** [paperclip-rs/paperclip#465]
Hi @tiagolobocastro, what do you think of making this repo opt in for Hacktoberfest?

I believe this repo has all the contribution guidelines and it has quite a lot of issues registered. So if you and other maintainers are ok I can create this required topic:

1. Add the “hacktoberfest” topic to your repository to opt-in to Hacktoberfest and indicate you’re looking for contributions.

2. Apply the “hacktoberfest” label to issues you want contributors to help with in your GitHub or GitLab project.

**Comment by tiagolobocastro** [comment]
Sounds good to me @dunnock !

**Comment by dunnock** [comment]
Sorry it appears I cannot add topic can you please add https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics#about-topics Thanks!

**Comment by dunnock** [comment]
Coll I see it's done, I've also added labels to some issues
