### ISSUE TITLE
Requests for Swagger Files Do Not Return Content-Type Header

### ISSUE THREAD

**Issue by mikemcdermottredjack** [paperclip-rs/paperclip#466]
Browsers will typically assume the `content-type` based upon the file delivered, but we have run into an issue where we have a web client making a misinterpretation based upon the lack of a `content-type` header.

I believe this can be traced down to this block of code: 

```
HttpResponse::Ok().body(
                                    SWAGGER_DIST
                                        .get_file(filename)
                                        .unwrap_or_else(|| {
                                            panic!("Failed to get file {}", filename)
                                        })
                                        .contents(),
```

Adding an `insert_header` that maps the filename to the `content-type` (assuming sane filenames) could resolve this issue.

**Comment by tiagolobocastro** [comment]
Yep that sounds reasonable to me

**Comment by mikemcdermottredjack** [comment]
https://github.com/paperclip-rs/paperclip/pull/467/files

**Comment by tiagolobocastro** [comment]
Yes, I believe so.
