### ISSUE TITLE
How to use Swagger UI

### ISSUE THREAD

**Issue by mike-lloyd03** [paperclip-rs/paperclip#475]
Maybe I am an idiot, but I am not understanding how to expose the Swagger UI.

Multiple places ([Changelog.md](https://github.com/paperclip-rs/paperclip/blob/master/CHANGELOG.md), #331, [tests](https://github.com/paperclip-rs/paperclip/blob/aac5bc734a470f46c31b727b859cf9089f22c0be/tests/test_app.rs#L1433)) indicate that I simply need to use `with_swagger_ui_at` to expose it. But when I do, the compiler yells at me.

```rust
use actix_web::{App, HttpServer};
use paperclip::actix::{web::scope, OpenApiExt};

mod models;
mod routes;

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(move || {
        App::new()
            .wrap_api()
            .service(scope("/api").service(routes::users::get_all))
            .with_json_spec_at("/spec")
            .with_swagger_ui_at("/swagger")
            .build()
    })
    .bind(("0.0.0.0", 8080))?
    .run()
    .await
}
```

```
  --> src/main.rs:14:14
   |
14 |             .with_swagger_ui_at("/swagger")
   |              ^^^^^^^^^^^^^^^^^^ method not found in `paperclip::actix::App<actix_web::app_service::AppEntry>`
```

Also, I don't see anything mentioned in the docs about this at docs.rs for `paperclip` or `paperclip_actix`.

Cargo.toml:
```toml
[dependencies]
actix-web = "4.2.1"
paperclip = { version = "0.7.1", features = ["actix4"] }
```

I'm on Rust 1.64.0

What crucial piece am I missing here?

**Comment by mike-lloyd03** [comment]
Yep. I'm an idiot.

```toml
paperclip = { version = "0.7.1", features = ["actix4", "swagger-ui"] }
```

**Comment by tiagolobocastro** [comment]
We've all been there, more than once :)
