### ISSUE TITLE
[Feature] Add support for Path/PathBuf type 

### ISSUE THREAD

**Issue by AzHicham** [paperclip-rs/paperclip#500]
Hello, 

Unfortunately paperclip does not support PathBuf as parameter of Schema. Of course it works well with String type, but currently my api's use PathBuf instead of String. 

Example this code will fail to compile : 
```
#[derive(Apiv2Schema, Debug, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct RoiRequestInput {
    pub path: PathBuf,
    pub level: u32,
}
```
With the following error : 
```
pub struct PathBuf {
     | ------------------
     | |
     | doesn't satisfy `PathBuf: Apiv2Schema`
     | doesn't satisfy `PathBuf: TypedData`
```

WDYT about including PathBuf as String ? 

Thanks

**Comment by AzHicham** [comment]
May be we wan simply add this : 
`impl_type_simple!(String, DataType::String);`
[cf the src code](https://paperclip-rs.github.io/paperclip/src/paperclip_core/v2/schema.rs.html#172)

**Comment by tiagolobocastro** [comment]
Yes I think that should work, happy to receive a PR for it :) Otherwise I'll try to get around this soon.
