### ISSUE TITLE
[Bug] Type mismatch

### ISSUE THREAD

**Issue by AzHicham** [paperclip-rs/paperclip#501]
Hello, 

I'm currently facing a sever bug while using Paperclip. 
Having this code : 

```
pub fn config<T: ServeSlide + 'static>() -> Scope {
    web::scope("/imgsrv")
        .route("/roi/{path:.*}+{level}", web::get().to(roi::<T>))
        ...
}
```
```
#[api_v2_operation]
pub async fn roi<T: ServeSlide>(
    input: web::Path<RoiRequestInput>,
) -> Result<Json<Vec<Roi>>, T::ErrorType> {
   ...
    Ok(Json(res))
}
```
```
#[derive(Apiv2Schema, Debug, Deserialize)]
pub struct RoiRequestInput {
    pub path: String,
    pub level: u32,
}
```
I get the following generated openapi schema: 

```
"/imgsrv/roi/{path}+{level}": {
      "get": {
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Roi"
              }
            }
          }
        },
        "parameters": [
          {
            "in": "path",
            "name": "path",
            "required": true,
            "type": "integer",
            "format": "int32",
            "pattern": ".*"
          },
          {
            "in": "path",
            "name": "level",
            "required": true,
            "type": "string"
          }
        ]
      }
    },
```

As you can see paperclip switch integer type with string 

Thanks for your help

**Comment by jonra1993** [comment]
I have a similar error in my path variables not have correct data

```rust
#[derive(Deserialize, Apiv2Schema)]
struct PathInfo {
    user_id: uuid::Uuid,
    friend: String,    
}

#[derive(Serialize, Apiv2Schema)]
struct IPostResponse<T> {
    message: String,
    data: T,
}

#[api_v2_operation]
#[get("/users/{user_id}/{friend}")] // <- define path parameters
async fn get_user(
    info: Path<PathInfo>,
    query: Query<QueryInfo>,
) -> Result<Json<IPostResponse<String>>, Error> {
    let result = if let Some(username) = &query.username {
        format!(
            "Welcome {}, user_id {}, username {}! ",
            info.friend, info.user_id, username
        )
    } else {
        format!("Welcome {}, user_id {}! ", info.friend, info.user_id)
    };
    let response = IPostResponse {
        data: result,
        message: String::from("Data got sucessfully"),
    };
    Ok(web::Json(response))
}
```

<img width="1600" alt="image" src="https://user-images.githubusercontent.com/23468720/230801692-868203dd-6377-4efb-8605-438e36580ed6.png">

**Comment by AzHicham** [comment]
Unfortunately not yet, 
I’ll try to fix it when I find some time :)

**Comment by tiagolobocastro** [comment]
Interesting...  seems like they're swapped around!

**Comment by mharkins-cosm** [comment]
I'm seeing the same thing with the parameter descriptions (as documented using doc comments).  Parameter 1 gets Parameter 2's description and vice versa.

**Comment by labmorales** [comment]
Has anyone found a way around this?

**Comment by labmorales** [comment]
Got around this by placing the path arguments in alphabetical order. So if you have a route like this
`/{user_id}/{app_id}/{env_id}` if you change it to `/{app_id}/{env_id}/{user_id}` it should work.

**Comment by tiagolobocastro** [comment]
I think I have a fix for this, I'll raise it soon.
A few things I noticed that should probably be addressed separately:
```rust
    #[get("/users/{ace}/{user_id}/{friend}")
    async fn get_user(
        ace: web::Path<bool>,
        friend: web::Path<String>,
        user_id: web::Path<u32>,
    );
```
Seems the names of the parameters get ignore completely, current code only cares about the order of the names in the path and the function parameter order.
Is this to allow things like this?
```rust
#[get("/users/{ace}/{user_id}/{friend}")
async fn get_user(_p: web::Path<(u32, bool, String)>) -> NoContent {
```

Then the final one:
```rust
#[derive(Deserialize, Apiv2Schema)]
    struct PathInfo {
        user_id: u32,
        ace: bool,
        friend: String,
    }
#[get("/users/{ace}/{user_id}/{friend}")]
    async fn get_user(_info: web::Path<PathInfo>) -> NoContent {
        NoContent
    }
```

In this case we have the object PathInfo and turns out its properties are store in a btreemap with the name as key, and thus why we have the ordering by name!
I'll raise a PR in the next couple of days for this last scenario with the struct, but I suspect the first ones will be tricky to solve at this point without a lot of changes...

**Comment by tiagolobocastro** [comment]
Would someone be able able to check if this helps?
https://github.com/paperclip-rs/paperclip/pull/504
I *think* I've improved things but I don't like how it currently works, though fixing it properly needs more proc-macro magic than I can handle at the moment.

**Comment by tiagolobocastro** [comment]
Anyone able to test the PR with their code before I merge it?

**Comment by jonra1993** [comment]
Hello @tiagolobocastro I have tested your fix and it works. 

Cargo.toml
```
......
paperclip = { git="https://github.com/paperclip-rs/paperclip.git", branch = "path-order", features = ["actix4", "swagger-ui", "uuid"] }
.....
```

<img width="1593" alt="image" src="https://github.com/paperclip-rs/paperclip/assets/23468720/9cc87962-b75b-4896-951b-db9dd0287126">

**Comment by tiagolobocastro** [comment]
Awesome thank you @jonra1993

**Comment by tiagolobocastro** [comment]
Hey folks, 0.8.1 is out, hopefully addresses everyone's issues. Let us know otherwise, thanks!

**Comment by mharkins-cosm** [comment]
@tiagolobocastro we're currently in the process of upgrading to 0.8.1 in our apps and it looks like it's resolved the issue for us... thank so much!
