### ISSUE TITLE
Typescript output

### ISSUE THREAD

**Issue by Poimen** [paperclip-rs/paperclip#503]
Hi,

I have been looking for a rsut cli that would be able to take in a openapi json document and output typescript/react-query files.

I got an example of:
paperclip -i api.json --bindings typescript

However, it doesn't seem like this is either supported anymore, or the information is very wrong.

Does this cli support typescript client generation?

Thanks,

**Comment by tiagolobocastro** [comment]
Generating clients in other languages would be nice but we simply don't have the bandwidth to do that as of today.
