### ISSUE TITLE
[request] [help] Ranged values

### ISSUE THREAD

**Issue by RaulTrombin** [paperclip-rs/paperclip#515]
There is some way/instruction on how to set ranged inputs?
something at the struct field like: [api_v2(min_value = 0)]

For enuns and direct type values it works pretty fine.

**Comment by RaulTrombin** [comment]
Tryed a mix of:
https://github.com/paperclip-rs/paperclip/blob/555a460cdfbc295edb504c3d7f441253a5c681ae/core/src/v2/models.rs#L519
and
https://paperclip-rs.github.io/paperclip/actix-security.html

```
#[derive(Apiv2Schema, Debug, Deserialize, Serialize)]
#[openapi(minimum=0, maximum=255)]
pub struct ApiNeopixel {
    #[openapi(minimum=0, maximum=255)]
    red: u8,
    green: u8,
    blue: u8,
}

```

no success yet:
![image](https://github.com/paperclip-rs/paperclip/assets/80598030/f0f8e2da-13a8-4f04-a8ad-b7533c56b5b6)

**Comment by tiagolobocastro** [comment]
Yeah a validator like that seems like a good idea.
Although in general we could also improve things, as with u8 the min and max should also be set?

**Comment by RaulTrombin** [comment]
> Yeah a validator like that seems like a good idea. Although in general we could also improve things, as with u8 the min and max should also be set?

I think it could be an optional field, if not set - It will take the minumum and maximum values from integer type.
But if defined you can set your own limits.

**Comment by tiagolobocastro** [comment]
Sorry about the long delay in addressing this..
With this I think the min/max are addressed for both your issues, please let me know otherwise.
