### ISSUE TITLE
[request] How to define multiple return http errors on api spec

### ISSUE THREAD

**Issue by RaulTrombin** [paperclip-rs/paperclip#517]
I'm validating my api using schemathesis,
It found an error with a function that receives invalid u8 values on i32 field, giving an error:
![image](https://github.com/paperclip-rs/paperclip/assets/80598030/d662ad5e-a01d-4994-a094-81f62512869d)

```
#[api_v2_operation]
#[post("v1/output/neopixel")]
async fn post_neopixel(json: web::Json<ApiNeopixel>) -> Result<Json<AnsPackage>, Error> {
    let neopixel = json.into_inner();
    let package = packages::set_neopixel(vec![[neopixel.red, neopixel.green, neopixel.blue]]);
    Ok(Json(package))
}
```

Actually the specs are generating like this:
![image](https://github.com/paperclip-rs/paperclip/assets/80598030/6f765cab-bb84-4922-ae86-3b712775d0d9)

How to add the other expected 400 error code?

**Comment by joaoantoniocardoso** [comment]
Check [this](https://github.com/mavlink/mavlink-camera-manager/pull/280/files#diff-b695292b0747f64154dc14c53d0ebc55d14e73d7f6603e8ee47f658916f12d3b out.

The idea is that you need to define a structure with your possible errors, defining their kind.

**Comment by tiagolobocastro** [comment]
There's some docs, albeit not great.. https://paperclip-rs.github.io/paperclip/actix-status-codes.html

**Comment by RaulTrombin** [comment]
thks!
