### ISSUE TITLE
Unable to find swagger components when developping locally

### ISSUE THREAD

**Issue by RaulTrombin** [paperclip-rs/paperclip#534]
```
  --> /home/raulvt/Documents/BR/paperclip/plugins/actix-web/src/lib.rs:46:28
   |
46 | static SWAGGER_DIST: Dir = include_dir!("$CARGO_MANIFEST_DIR/swagger-ui/dist");

```

`git submodule update --init --recursive`
Solve the issue, maybe we can add this step into make prepare routine (?)

**Comment by tiagolobocastro** [comment]
When I read "make prepare" I got quite confuse, I had forgotten that we have a makefile :)
Yes I think we can probably add that to the make prepare
