### ISSUE TITLE
`paperclip-macros` patch version `0.6.4` introduced a breaking change with min/max

### ISSUE THREAD

**Issue by Sufflope** [paperclip-rs/paperclip#542]
This patch version changes the `DefaultSchemaRaw` derived struct by adding properties to it in commit 135096f9fd0c72a42929b4e188d4894d6b36fd56.

My problem is that I have a proc-macro crate where I generate code, including a hand-written `Apiv2Schema` `impl` for the type:

```rust
impl paperclip::v2::schema::Apiv2Schema for #ident {
    fn name() -> Option<String> {
        Some(stringify!(#ident).to_string())
    }
    fn raw_schema() -> paperclip::v2::models::DefaultSchemaRaw {
        paperclip::v2::models::DefaultSchemaRaw {
            name: Self::name(),
            reference: None,
            title: None,
            description: Some(#description.to_string()),
            data_type: Some(paperclip::v2::models::DataType::String),
            format: None,
            example: Some(serde_json::json!(#example)),
            properties: ::std::collections::BTreeMap::new(),
            items: None,
            enum_: vec![],
            extra_props: None,
            required: ::std::collections::BTreeSet::new(),
        }
    }
}
```

The issue is that I (and I guess other `paperclip` users) only add a dependency to the base crate, not the macros directly, The macro crate is pulled transitively, and `0.6.4` is semver-compatible with `0.6.3`, so if I run `cargo update` in my end project (which depends on `paperclip` and my internal crate) to update my dependencies for housekeeping, `paperclip-macros` gets updated to `0.6.4` but then my project does not compile anymore because my proc-macro crate generates incomplete `DefaultSchemaRaw` structs.

IDK what the course of action would be? I would say yank `paperclip-macros` `0.6.x` for `x > 3` and bump it to `0.7.0`, and release patch versions of `paperclip` for those which need those min/max params, with a dependency to `paperclip-macros` `0.7`?

**Comment by tiagolobocastro** [comment]
Ah bummer... perhaps DefaultSchemaRaw should not have been a public api with public fields..
Anyway, seems probably we should indeed yank it out, release a "fixed" 0.6.5, and then a "breaking" 0.7.0
Meanwhile I think you can run `cargo update -p paperclip-macros --precise 0.6.3`
